import { createServer } from 'node:http';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('.', import.meta.url));
const publicDir = join(root, 'public');
// En local les données vivent dans ./data. En ligne, BATCH_DATA_DIR pointe
// vers un disque persistant (Render/Railway) afin de ne jamais perdre le profil.
const dataDir = process.env.BATCH_DATA_DIR || join(root, 'data');
const dbFile = join(dataDir, 'user-data.json');
const recipesFile = join(dataDir, 'recipes.json');
const mime = { '.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.css':'text/css; charset=utf-8','.webmanifest':'application/manifest+json' };
async function readJson(file, fallback){ try{return JSON.parse(await readFile(file,'utf8'));}catch{return fallback;} }
async function body(req){ let text='';for await(const part of req)text+=part;return JSON.parse(text||'{}'); }
async function save(data){ await mkdir(dataDir,{recursive:true});await writeFile(dbFile,JSON.stringify(data,null,2)); }
const server=createServer(async(req,res)=>{ try{
  const url=new URL(req.url,'http://localhost');
  if(url.pathname==='/api/health'){res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify({ok:true}));}
  if(url.pathname==='/api/recipes'&&req.method==='GET'){const recipes=await readJson(recipesFile,[]);res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify(recipes));}
  if(url.pathname==='/api/recipes'&&req.method==='POST'){const recipes=await readJson(recipesFile,[]),payload=await body(req),name=String(payload.name||'').trim();if(!name){res.writeHead(400,{'content-type':'application/json'});return res.end(JSON.stringify({error:'Nom requis'}));}const recipe={id:crypto.randomUUID(),name,meal:['breakfast','lunch','dinner','snack'].includes(payload.meal)?payload.meal:'dinner',tags:Array.isArray(payload.tags)?payload.tags.map(String).slice(0,12):[],kcal:Math.max(0,Number(payload.kcal)||500),protein:Math.max(0,Number(payload.protein)||25),cost:Math.max(0,Number(payload.cost)||10),image:String(payload.image||''),ingredients:Array.isArray(payload.ingredients)?payload.ingredients.map(String).filter(Boolean).slice(0,30):[],steps:Array.isArray(payload.steps)?payload.steps.map(String).filter(Boolean).slice(0,20):[],equipment:Array.isArray(payload.equipment)?payload.equipment.map(String).slice(0,5):[],source:String(payload.source||'Proposée par toi'),createdAt:new Date().toISOString()};recipes.unshift(recipe);await mkdir(dataDir,{recursive:true});await writeFile(recipesFile,JSON.stringify(recipes,null,2));res.writeHead(201,{'content-type':'application/json'});return res.end(JSON.stringify(recipe));}
  if(url.pathname==='/api/recipe-suggest'&&req.method==='GET'){const query=url.searchParams.get('name')?.trim();if(!query){res.writeHead(400,{'content-type':'application/json'});return res.end(JSON.stringify({error:'Nom requis'}));}try{const normalized=query.toLocaleLowerCase('fr').normalize('NFD').replace(/[\u0300-\u036f]/g,''),aliases={pate:'pasta',pates:'pasta',creme:'creamy',poulet:'chicken',boeuf:'beef',saumon:'salmon',thon:'tuna',poisson:'fish',riz:'rice',nouille:'noodles',nouilles:'noodles',curry:'curry',sandwich:'sandwich',wrap:'wrap',salade:'salad',fromage:'cheese',tomate:'tomato',legume:'vegetable',legumes:'vegetable',epice:'spicy',epices:'spicy'},tokens=normalized.split(/[^a-z]+/).filter(token=>token.length>2),terms=[query,...tokens.map(token=>aliases[token]||token)].filter((term,index,list)=>term&&list.indexOf(term)===index).slice(0,6),responses=await Promise.all(terms.map(async term=>{try{const response=await fetch(`https://www.themealdb.com/api/json/v1/1/search.php?s=${encodeURIComponent(term)}`,{signal:AbortSignal.timeout(7000)});const data=await response.json();return data.meals||[]}catch{return []}})),needle=[...tokens,...tokens.map(token=>aliases[token]).filter(Boolean)],meals=responses.flat().filter((meal,index,list)=>list.findIndex(item=>item.idMeal===meal.idMeal)===index).sort((a,b)=>{const score=meal=>needle.reduce((sum,word)=>sum+(String(meal.strMeal).toLowerCase().includes(word)?3:String(meal.strCategory||'').toLowerCase().includes(word)?1:0),0);return score(b)-score(a)}).slice(0,5),toDraft=meal=>{const ingredients=[];for(let index=1;index<=20;index++){const ingredient=String(meal[`strIngredient${index}`]||'').trim(),measure=String(meal[`strMeasure${index}`]||'').trim();if(ingredient)ingredients.push(`${measure?`${measure} `:''}${ingredient}`.trim())}const steps=String(meal.strInstructions||'').split(/\r?\n|(?<=[.!?])\s+(?=[A-Z])/).map(step=>step.trim()).filter(step=>step.length>18).slice(0,10);return {name:meal.strMeal,meal:'dinner',image:meal.strMealThumb,ingredients,steps:steps.length?steps:['Prépare les ingrédients puis suis la recette source.'],source:`Fiche trouvée : ${meal.strSource||'TheMealDB'}`}};if(!meals.length)throw new Error('not found');res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify({query,candidates:meals.map(toDraft)}));}catch{res.writeHead(404,{'content-type':'application/json'});return res.end(JSON.stringify({error:'Aucune idée proche trouvée. Crée-la en version complète.'}));}}
  if(url.pathname==='/api/me'&&req.method==='GET'){const state=await readJson(dbFile,{profile:{},history:[],measurements:[],fridge:[]});state.fridge??=[];res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify(state));}
  if(url.pathname==='/api/me'&&req.method==='PUT'){const state=await readJson(dbFile,{profile:{},history:[],measurements:[],fridge:[]});state.profile={...state.profile,...await body(req)};await save(state);res.writeHead(204);return res.end();}
  if(url.pathname==='/api/plans'&&req.method==='POST'){const state=await readJson(dbFile,{profile:{},history:[],measurements:[],fridge:[]}),payload=await body(req),createdAt=new Date().toISOString();state.history??=[];state.fridge??=[];const plan={id:crypto.randomUUID(),createdAt,...payload};state.history.unshift(plan);for(const item of payload.fridgeItems||[]){const total=Math.max(1,Number(item.total)||4),fresh=Math.min(total,Math.max(0,Number(item.fresh)||0));state.fridge.unshift({id:crypto.randomUUID(),planId:plan.id,createdAt,recipeName:String(item.recipeName||'Recette'),total,remaining:total,fresh,frozen:total-fresh});}await save(state);res.writeHead(201,{'content-type':'application/json'});return res.end(JSON.stringify(plan));}
  if(url.pathname==='/api/fridge'&&req.method==='GET'){const state=await readJson(dbFile,{fridge:[]});res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify(state.fridge||[]));}
  if(url.pathname.startsWith('/api/fridge/')&&req.method==='PATCH'){const state=await readJson(dbFile,{fridge:[]}),id=url.pathname.split('/').pop(),changes=await body(req),item=(state.fridge||[]).find(row=>row.id===id);if(!item){res.writeHead(404);return res.end();}for(const key of ['remaining','fresh','frozen'])if(Number.isFinite(Number(changes[key])))item[key]=Math.max(0,Number(changes[key]));await save(state);res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify(item));}
  if(url.pathname==='/api/measurements'&&req.method==='POST'){const state=await readJson(dbFile,{profile:{},history:[],measurements:[]});state.measurements??=[];const measurement={id:crypto.randomUUID(),createdAt:new Date().toISOString(),...await body(req)};state.measurements.unshift(measurement);await save(state);res.writeHead(201,{'content-type':'application/json'});return res.end(JSON.stringify(measurement));}
  const path=url.pathname==='/'?'/index.html':url.pathname;if(path.includes('..'))throw new Error('Bad path');const file=join(publicDir,path);const content=await readFile(file);const headers={'content-type':mime[extname(file)]||'application/octet-stream'};if(path==='/index.html')headers.Link='</manifest.webmanifest>; rel="manifest"';res.writeHead(200,headers);res.end(content);
 }catch{res.writeHead(404,{'content-type':'text/plain; charset=utf-8'});res.end('Page introuvable');}});
// PORT est fourni automatiquement par la plupart des hébergeurs Node.
const port=Number(process.env.PORT||process.env.BATCH_APP_PORT||3000);
server.listen(port,'0.0.0.0',()=>console.log(`Batch is ready on http://localhost:${port}`));
